### ISSUE TITLE
Can you add an implementation with an example on the fastify server?

### ISSUE THREAD

**Issue by egoson** [fastify/busboy#101]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

The problem is that I do not quite understand how to pass busboy to the pipe, based on examples from the busboy library

**Comment by Uzlopak** [comment]
We use our busboy fork in @fatsify/multipart. Plrease refer to that plugin to figure out how it is used ;).
