### ISSUE TITLE
Uploading an excel document is giving an error

### ISSUE THREAD

**Issue by joostoudeman** [fastify/busboy#107]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.10.2

### Plugin version

1.2.0

### Node.js version

18.12.1

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

22.04.01

### Description

I have a nestjs project using fastify.
Today I updated all my dependencies, and as a result it seems the upload of an excel file gives this error:

```
[Nest] 74345  - 01/06/2023, 5:37:32 PM   ERROR [ExceptionsHandler] Premature close
Error: Premature close
    at new NodeError (node:internal/errors:393:5)
    at onclose (node:internal/streams/end-of-stream:142:30)
    at processTicksAndRejections (node:internal/process/task_queues:77:11)
```

Some digging brought me to this transient dependency of busboy. pinning this to 1.1.0 fixes my problem, but it might be something you want to look into.

if it helps, the mimetype is application/vnd.openxmlformats-officedocument.spreadsheetml.sheet

### Steps to Reproduce

This is using nestje configured to use fastify

1. make an endpoint to recieve a file
2. send an excel file via a multipart form

### Expected Behavior

I expect the file to arrive in the endpoint to be processed

**Comment by Uzlopak** [comment]
Plesae provide a repo to clone so that i can inestigate the issue.

**Comment by joostoudeman** [comment]
I'll get on that, might be a few days, so please be patient.

**Comment by Eomm** [comment]
Could it https://github.com/fastify/busboy/pull/81 be related?

**Comment by Uzlopak** [comment]
Possible. But also we need a failing test case to investigate why this happens.

**Comment by Uzlopak** [comment]
@Eomm 

Yes. git bisecting shows that that commit is the culprit.

**Comment by Eomm** [comment]
Released the rollback https://github.com/fastify/busboy/releases/tag/v1.2.1

**Comment by mn4367** [comment]
For what it's worth: I also had a problem (on Fastify 4.11.0 and Node 16.3.0).

Using
```
const pump = util.promisify(pipeline);
await pump(someStreamFromAFileUpload, writeStream);
```
in a Fastify application to handle file uploads `await pump` never returned. I was able to fix this with setting the highWaterMark size on `writeStream` to `5 * 1024 * 1024`, lower values always lead to a never returning `await` eventually.

However this 'fix' smelled a bit since it seems contradictory to everything which can be found in the Node docs for piping streams.
