### ISSUE TITLE
Malformed boundary does not throw

### ISSUE THREAD

**Issue by gurgunday** [fastify/busboy#121]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

X

### Plugin version

X

### Node.js version

20

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

Latest

### Description

I want to merge @fastify/busboy into undici, but a [specific test](https://github.com/nodejs/undici/blob/f08379c55857819f258b0cdc5ad6f944074e2c42/test/fetch/client-fetch.js#L253) will not currently pass:

```js
test('busboy emit error', async (t) => {
  t.plan(1)
  const formData = new FormData()
  formData.append('field1', 'value1')

  const tempRes = new Response(formData)
  const formRaw = await tempRes.text()

  const server = createServer((req, res) => {
    res.setHeader('content-type', 'multipart/form-data; boundary=wrongboundary')
    res.write(formRaw)
    res.end()
  })
  t.teardown(server.close.bind(server))

  const listen = promisify(server.listen.bind(server))
  await listen(0)

  const res = await fetch(`http://localhost:${server.address().port}`)
  await t.rejects(res.formData(), 'Unexpected end of multipart data')
})
```

Busboy ignores this input rather than throwing for malformed boundary

I [found within the code](https://github.com/fastify/busboy/blob/dccf57523b14c4c70a9704266737a7cdbb2526eb/deps/dicer/lib/Dicer.js#L54) a part that should throw in this case (if I'm not mistaken), but it's not working in practice

I will take a look at this myself, but if anyone could help, it would be highly appreciated

### Steps to Reproduce

Run this test after replacing busboy with @fastify/busboy in undici:

```js
test('busboy emit error', async (t) => {
  t.plan(1)
  const formData = new FormData()
  formData.append('field1', 'value1')

  const tempRes = new Response(formData)
  const formRaw = await tempRes.text()

  const server = createServer((req, res) => {
    res.setHeader('content-type', 'multipart/form-data; boundary=wrongboundary')
    res.write(formRaw)
    res.end()
  })
  t.teardown(server.close.bind(server))

  const listen = promisify(server.listen.bind(server))
  await listen(0)

  const res = await fetch(`http://localhost:${server.address().port}`)
  await t.rejects(res.formData(), 'Unexpected end of multipart data')
})
```

### Expected Behavior

Test should pass

**Comment by gurgunday** [comment]
Ref PR:

https://github.com/nodejs/undici/pull/2211

**Comment by Uzlopak** [comment]
Why should it actually throw.

**Comment by gurgunday** [comment]
That's what the undici unit test demands, and more importantly what the browser behavior is

Normal busboy does throw there, so I'm inclined to believe one of our patches prevents/ignores the error

**Comment by Uzlopak** [comment]
undici throws, ok. Where is it defined that a non matching boundary should throw in the first place?

Anyhow: It should be actually no problem to patch it accordingly to throw.

**Comment by gurgunday** [comment]
> Where is it defined that a non matching boundary should throw in the first place?

I actually couldn't spot it in the multipart formdata RFC, maybe they mimicked browser behavior (i.e., Safari)

**Comment by KhafraDev** [comment]
It's part of the fetch spec (https://fetch.spec.whatwg.org/#dom-body-formdata):
```
[...] Parse bytes, using the value of the `boundary` parameter from mimeType, per the rules set forth in Returning Values from Forms: multipart/form-data.
[...] If that fails for some reason, then [throw](https://webidl.spec.whatwg.org/#dfn-throw) a [TypeError](https://webidl.spec.whatwg.org/#exceptiondef-typeerror).
```

Returning a value from a malformed body doesn't seem like correct behavior to me - the body can't be parsed if the boundary is mismatched, but the parsing "succeeds" in the sense that an object is returned.

**Comment by KhafraDev** [comment]
In the RFC:
```
   In the case of multipart entities, in which one or more different
   sets of data are combined in a single body, a "multipart" media type
   field must appear in the entity's header.  The body must then contain
   one or more body parts, each preceded by a boundary delimiter line,
   and the last one followed by a closing boundary delimiter line.
```

note that the RFC says the body *must* contain > 1 parts and *must* be delimited with the boundary (new lines, etc.)

**Comment by Uzlopak** [comment]
Ok, you convinced me. 

Unfortunately i am currently not that deep in the codebase. But if you could provide a PR, i would review it asap.

**Comment by gurgunday** [comment]
Now all we need is a semver major release 🤠

I do wanna do some refactoring too but nothing involving behavior change

**Comment by Uzlopak** [comment]
I have to bump @kibertoad to release a new major. I dont think I have npm publish rights.

Also I want to change to node-tap, so that tests, are faster 

Also come to discord if possible.. have to coordinate with you.

**Comment by gurgunday** [comment]
I’d love to! Where can I find the Discord server

**Comment by Uzlopak** [comment]
Click here: [![Discord](https://img.shields.io/discord/725613461949906985)](https://discord.gg/fastify)

**Comment by gurgunday** [comment]
@climba03003 @Eomm

Although breaking, this was an important change that aligned busboy with the RFC

It will also let us merge this more performant version into undici

Can we make a release? I don't want to take initiative without asking 😁

**Comment by gurgunday** [comment]
Latest results:

```shell
{ cpu: { brand: 'M1', speed: '2.4 GHz' } }
| Node    | Option         | Msecs/op       | Ops/sec  | V8                    |
| ------- | -------------- | -------------- | -------- | --------------------- |
| 20.6.0  | fastify-busboy | 0.110915 msecs | 9015.906 | V8 11.3.244.8-node.14 |
| 20.6.0  | busboy         | 0.207797 msecs | 4812.393 | V8 11.3.244.8-node.14 |
```

**Comment by gurgunday** [comment]
@mcollina can you move this under the plugins team?

**Comment by kibertoad** [comment]
@gurgunday I can push out a release today

**Comment by gurgunday** [comment]
Alright, thanks!

Just to restate the obvious, this was a breaking change
