### ISSUE TITLE
remove fork reference

### ISSUE THREAD

**Issue by Uzlopak** [fastify/busboy#130]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

I think we should remove the fork reference.

**Comment by Eomm** [comment]
It is not clear: should we drop the fork?
I read that the origin repo has been updated - doesn't it?

**Comment by Uzlopak** [comment]
No. I dont want to delete this repository. I want to remove the fork reference. 

![image](https://github.com/fastify/busboy/assets/5059100/15f141df-e321-42f2-a918-f34820460172)

**Comment by gurgunday** [comment]
Yeah, we don't have this fork reference in [fastify/send](https://github.com/fastify/send) for instance

It just mentions that it's a fork

**Comment by gurgunday** [comment]
Also, not a huge problem for me, but it would be more consistent to have this plugin under the Plugins Team in my opinion

**Comment by Uzlopak** [comment]
The benefit is, that it will then be in search results of github and I guess it will trigger an indexing of this repository so we can also search in this repository. Also it avoids the issue, that if you work on this fork, that the PR view wants to merge to the upstream repository (this annoyed mcscdex in the past).

**Comment by Uzlopak** [comment]
@mcollina 
I tried to make an unfork request, but I cant request that because i am not an admin of the project. Can you please do the extract fork request?

**Comment by Eomm** [comment]
Where?

I thought it was necessary to remove a `git remote`

**Comment by Uzlopak** [comment]
@Eomm 
@mcollina 

https://support.github.com/contact?tags=rr-forks&subject=Detach%20Fork&flow=detach_fork

**Comment by Uzlopak** [comment]
@jsumners 

Can you please do the detach fork request?

**Comment by Eomm** [comment]
Done


<details>
  <summary>Click to expand!</summary>

```


### Transcript:
- **from_agent**: Hi, Eomm.
- **from_agent**: A fork is a copy of a repository. Forking a repository allows you to freely experiment with changes without affecting the original project.
- **from_agent**: Are you looking to delete a fork or detach/extract a fork?
- **from_agent**: Detach - To create a new fork network containing only this repository. All of its sub-forks are re-parented and stay in the original fork network.
- **from_agent**: Extract - To move the fork and all its subforks into a new network. This repository becomes the new root.  Delete Detach/Extract
- **from_user**: *Detach/Extract*
- **from_agent**: Please enter the owner/repository-name or the URL of the forked repository that you'd like detached/extracted
- **from_user**: *fastify/busboy*
- **from_agent**: Checking repository status, please wait...
- **from_agent**: Have you committed to this fork?  Yes No
- **from_user**: *Yes*
- **from_agent**: fastify/busboy has child forks; what should we do with these? Commonly you'll want to bring the child forks along with you when detaching your fork from the upstream repository.  Bring the child forks with the repository Leave the child forks behind
- **from_user**: *Bring the child forks with the repository*
- **from_agent**: To help improve GitHub, please tell us why you'd like to detach the fork  Please select a choice Contributions to the repository aren't visible The repository isn't included in search results The repository was initially based on a boilerplate or template repository The repository has diverged significantly from its parent The intended audience, purpose, or security posture of the repository have changed I need to use a feature that isn't available because the repository is a fork I need to use my own GitLFS data allowances and/or data-packs
- **from_user**: *The repository has diverged significantly from its parent*
- **from_agent**: Note: GitLFS objects may not be available immediately after fork detachment. Please allow up to an hour for replication to complete.
- **from_agent**: Creating a ticket for your request...
- **from_agent**: Ticket created, we'll update you when the detach/extract operation has been processed.
- **from_agent**: All done. Thank you for using Virtual Assistant.
- **from_agent**: Did this help you?  Yes No
```
</details>
