### ISSUE TITLE
Fails to parse request stream on bun

### ISSUE THREAD

**Issue by sean256** [fastify/busboy#139]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

2.1.0

### Node.js version

Bun v1.0.15

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

14.0

### Description

This is related to
- https://github.com/fastify/fastify-multipart/issues/498
- https://github.com/oven-sh/bun/issues/5265

I understand if bun support is beyond the scope of this project, but I did do some exploring. From what I can tell the root issue is in this library (or bun!).

What I did was wrote the failing request stream to a file. Then in the root of this project I stream that file into busboy and listen for fields and files. When running with `node` the file and field are found. When running with `bun` neither events are emitted.

At the root 
```js
'use strict'

const fs = require('fs')
const Busboy = require('.')

const busboy = new Busboy({
  headers: {
    'content-type': 'multipart/form-data; boundary=__X_PAW_BOUNDARY__'
  }
})

busboy.on('field', function (key) {
  console.log('field found', key)
})
busboy.on('file', function (fieldname, stream) {
  console.log('file found', fieldname)

  stream.on('end', () => {
    console.log(`File [${fieldname}] Finished`)
  })
})
busboy.on('finish', function () {
  console.log('finished')
})

// stream request dump to busboy
const readable = fs.createReadStream('./test/dump')
readable.pipe(busboy)
```

The request dump: https://drive.google.com/file/d/19_y4fy5pwi6_xDYblHhSp0bEIMhNSiYS/view?usp=share_link

```bash
node busboy-test.js
bun busboy-test.js
```

### Steps to Reproduce

Run the above script

**Comment by Jarred-Sumner** [comment]
This is a bug in Bun, not in busboy

**Comment by Uzlopak** [comment]
Closing as bun related
