### ISSUE TITLE
Improve test coverage

### ISSUE THREAD

**Issue by kibertoad** [fastify/busboy#25]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

We have around 50% code coverage.
We can do better.

**Comment by Uzlopak** [comment]
We have now better coverage.

test coverage in master:
```
Statements   : 65.55% ( 940/1434 )
Branches     : 54.82% ( 506/923 )
Functions    : 71.9% ( 87/121 )
Lines        : 64.87% ( 857/1321 )
```

Should we increase the hard coded limits?

Curently:
```
    "lines": 51,
    "statements": 51,
    "functions": 49,
    "branches": 43
```

or maybe we wait till we merge #50 , which results that our test coverage will increase drastically
test coverage in replace-encodings branch
```
Statements   : 93.53% ( 810/866 )
Branches     : 86.8% ( 454/523 )
Functions    : 95.45% ( 63/66 )
Lines        : 96.41% ( 727/754 )
```

**Comment by kibertoad** [comment]
We should!

**Comment by Uzlopak** [comment]
Yeah.

```
=============================== Coverage summary ===============================
Statements   : 95.52% ( 812/850 )
Branches     : 90.34% ( 449/497 )
Functions    : 95.45% ( 63/66 )
Lines        : 97.07% ( 731/753 )
================================================================================
```

**Comment by gurgunday** [comment]
Alright, just closing this to prevent duplicates

And I chose this one because the coverage was _improved_ technically, as the title describes :D

Now we go for [100%](https://github.com/fastify/busboy/issues/126) 🚀
