### ISSUE TITLE
Handle empty filenames as fields instead of files

### ISSUE THREAD

**Issue by kibertoad** [fastify/busboy#26]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

When crafting browser requests it doesn't seem possible to leave out the filename in case you want to send a blob:

```js
const body = new FormData();
body.append('json', new Blob(['{"foo":"bar"}'], {type: 'application/json'}));
fetch('/test', {method: 'POST', body});
```

Uses "glob" as filename.

```js
const body = new FormData();
body.append('json', new Blob(['{"foo":"bar"}'], {type: 'application/json'}), '');
fetch('/test', {method: 'POST', body});
```

Uses "" as filename.

```js
const body = new FormData();
body.append('json', new Blob(['{"foo":"bar"}'], {type: 'application/json'}), null);
fetch('/test', {method: 'POST', body});
```

Uses "null" as filename.

Therefore such requests are handled as file because of this undefined check:
https://github.com/mscdex/busboy/blob/master/lib/types/multipart.js#L174

Is it reasonable to also accept parts with empty filenames as fields? Wouldn't a real file always have a filename?

I think that this could be seen as breaking change.

A minor change would be adding an option for a custom filtering handler which let the user decide whether a specific part should be handled as file or field.

**Comment by kibertoad** [comment]
Originally brought up by @cyantree in https://github.com/fastify/fastify-multipart/issues/292

**Comment by cyantree** [comment]
Thanks @kibertoad for preparing the fork and migrating this issue. I'll prepare a pull request for it later.

**Comment by cyantree** [comment]
Will be handled through #53
