### ISSUE TITLE
Streamsearch refactoring for better performance

### ISSUE THREAD

**Issue by Uzlopak** [fastify/busboy#35]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

We should consider to refactor the StreamSearch-component. Our benchmark is actually working with in memory, and I think that 4 GB/s is kind of slow. If it would be filesystem, than I guess, 4 GB/s is good, but in-memory seems to be slow. Maybe I am just expecting too much?

I wrote the unit tests to actually write a drop-in replacement. I started to write it multiple times, but I didnt succeeded, unfortunately. 
I guess, we could do alot of that searching per character with Buffer.indexOf and other "modern" node functionality.

Maybe you @kibertoad  or @mcollina  could write a high performance one? I thought of @mcollina  because he also wrote split2 npm package, which does something similar. 

![Screenshot from 2021-11-29 13-47-53](https://user-images.githubusercontent.com/5059100/143901996-926aadbb-aa73-4306-b4fa-b465de43e77b.png)

**Comment by kibertoad** [comment]
Matteo already said that he doesn't have time for this project, so I wouldn't count on that.
That said, I don't think we need to solve all the problems immediately. Maybe over time larger community will build something better and we could use it. For now we should improve what is easily within reach :)

**Comment by Uzlopak** [comment]
Allright, then we just keep this issue open as a reminder, where we could gain potentially more performance if we have time for heavy lifting ;).

**Comment by Uzlopak** [comment]
With PR #36 we get to 10-12 GB/s. But the hunt for more performance continues...
