### ISSUE TITLE
Add Input validation

### ISSUE THREAD

**Issue by Uzlopak** [fastify/busboy#37]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Wie should Check If the options passed to busboy are valid and if not throw TypeErrors.

https://github.com/mscdex/busboy/pull/207

If you agree @kibertoad  I would prepare a PR

**Comment by kibertoad** [comment]
I think I already merged PR based on issue 207, but we probably should review all ootions. Also fail-fast on creation would be better than the one on runtime we have one.

**Comment by Uzlopak** [comment]
Awesome!
