### ISSUE TITLE
Potential Code improvements in other forks

### ISSUE THREAD

**Issue by Uzlopak** [fastify/busboy#43]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Code we should check for validity and potential source for new features

https://github.com/pirxpilot/dicer/commit/93922c05273e4dd7e4064b288c17f1f3b8d42cb3
https://github.com/pirxpilot/dicer/commit/fb36ab9933518f6b98b918710e38f86a901a834b
https://github.com/pirxpilot/dicer/commit/69c09a673d5147665b26c9506034095cecaf7768
https://github.com/pirxpilot/dicer/commit/a6aa5d82b2692fbe9a4111b672d7dadec4f22287
https://github.com/peterfirst/dicer/commit/f4d1aa67c489d5832be28ab42a5d8d55e0d70662
https://github.com/jonruttan/dicer/commit/9a62b87b81a843bee8937802be8dfd8ed20938d8
https://github.com/jonruttan/dicer/commit/60ea418df4c7627718bac32f6032b81011f936e5
https://github.com/chrishiestand/busboy/commit/e7a138480302ecea287f4f2ce25d071f4748f479
https://github.com/mnmly/busboy/commit/9c710522db0a6c9a649b8418bfb67d25252f42ef
https://github.com/rangyf/busboy/commit/ce1ff1b3e304d86d9c1764fe617d79ce5e6bfefe

**Comment by Uzlopak** [comment]
@rangyf

Why did you add the drain event in your commit?

**Comment by Uzlopak** [comment]
@mnmly
Where does the content disposition attachment come in handy? Where is it actually specified?

**Comment by rangyf** [comment]
> @rangyf
> 
> Why did you add the drain event in your commit?

well, sorry it's been a while and i don't remember the details. what i can recall is that i was sending multiple files along with other string-valued form fields within a single http request.

**Comment by kibertoad** [comment]
@Uzlopak No more useful code left there?

**Comment by Uzlopak** [comment]
We should rather look what mscdex did in his refactored projects :)
