### ISSUE TITLE
Demand support ESM

### ISSUE THREAD

**Issue by xulsp** [fastify/busboy#60]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

```javascript
// please support import
import Busboy from "@fastify/busboy"

```

```javascript
// lib/main.js
// add the line
module.exports.default = Busboy
```

**Comment by kibertoad** [comment]
Sounds good, I'll do the change.

**Comment by kibertoad** [comment]
Implemented
